spring:
  batch:
    initialize-schema: ALWAYS
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

  main:
    allow-bean-definition-overriding: true
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

datasource:
  primary:
    driver-class-name: "com.mysql.jdbc.Driver"
    jdbc-url: "jdbc:mysql://localhost:3306/batchlog?serverTimezone=UTC"
    username: root
    password: rostov
  from:
    driver-class-name: "com.mysql.jdbc.Driver"
    jdbc-url: "jdbc:mysql://localhost:3306/springbooks?serverTimezone=UTC"
    username: root
    password: rostov


